### ISSUE TITLE
Works only if --no-drillholes option is set

### ISSUE THREAD

**Issue by Gasman2014** [yaqwsx/PcbDraw#11]
I have managed to get this to work on macOS (I had had to copy a system python executable into Kicad and stick lxml into he associated site-packages. 

The script runs but only if I select the --no-drillholes option, otherwise it fails with the following memory leak issue.

Kicad nightly from July 17 (which has been stable for me for a while).

```
✔ xxxxxxxx:PcbDraw [ master | ✚ 1 …2 ] ➭ ./pcbdraw.py ../PcbDraw-Lib/KiCAD-base/  --no-drillholes out2.svg /Users/xxxxxx/EDA_Workspace/trial_git/ThermocoupleLogger.kicad_pcb
Namespace(board='/Users/xxxxxxxx/EDA_Workspace/trial_git/ThermocoupleLogger.kicad_pcb', libraries=['../PcbDraw-Lib/KiCAD-base/'], list_components=False, no_drillholes=True, output='out2.svg', placeholder=False, remap=None, style=None)
Please ignore following debug output of KiCAD Python API
End of KiCAD debug output
/Volumes/SSD/workspace/osx-kicad-adam-head/kicad/common/lset.cpp(769): assert "unsigned( aLayer ) < PCB_LAYER_ID_COUNT" failed in ToLAYER_ID().
Warning: component 'MountingHole_5.5mm' from library 'Mounting_Holes' was not found
Warning: component 'MountingHole_3.2mm_M3' from library 'Mounting_Holes' was not found
Warning: component 'TO-220_Vertical' from library 'TO_SOT_Packages_THT' was not found
Warning: component 'TO-126_Vertical' from library 'TO_SOT_Packages_THT' was not found
....


✔ xxxxxxxxx:PcbDraw [ master | ✚ 1 …2 ] ➭ ./pcbdraw.py ../PcbDraw-Lib/KiCAD-base/  out2.svg /Users/xxxxxxxx/EDA_Workspace/trial_git/ThermocoupleLogger.kicad_pcb
Namespace(board='/Users/johnpateman/EDA_Workspace/trial_git/ThermocoupleLogger.kicad_pcb', libraries=['../PcbDraw-Lib/KiCAD-base/'], list_components=False, no_drillholes=False, output='out2.svg', placeholder=False, remap=None, style=None)
Please ignore following debug output of KiCAD Python API
End of KiCAD debug output
/Volumes/SSD/workspace/osx-kicad-adam-head/kicad/common/lset.cpp(769): assert "unsigned( aLayer ) < PCB_LAYER_ID_COUNT" failed in ToLAYER_ID().
Traceback (most recent call last):
  File "./pcbdraw.py", line 463, in <module>
    wrapper.append(get_board_substrate(board, style, not args.no_drillholes))
  File "./pcbdraw.py", line 265, in get_board_substrate
    container.append(get_hole_mask(board))
  File "./pcbdraw.py", line 314, in get_hole_mask
    pos = pad.GetPosition()
AttributeError: 'SwigPyObject' object has no attribute 'GetPosition'
swig/python detected a memory leak of type 'DLIST_ITERATOR_WRAPPER< D_PAD > *', no destructor found.
```

**Comment by yaqwsx** [comment]
There was a change in the Python API in the nightly builds. I pushed a fix for that.
