### ISSUE TITLE
v1.0.0 wheel contains pcbdraw.py, but is missing in source

### ISSUE THREAD

**Issue by agners** [yaqwsx/PcbDraw#126]
I've noticed that when installing PcbDraw v1.0.0 from PyPI, I get `pcbdraw.py` deployed as well. However, building from  source (either tag v1.0.0 from this repository or the source tarball from PyPI), the same file is missing. Therefor, also importing fails was well:

```
>>> import pcbdraw.pcbdraw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pcbdraw.pcbdraw'

```

I've noticed that while working with Pinion:

```
Traceback (most recent call last):
  File "/home/sag/.local/bin/pinion", line 5, in <module>
    from pinion.ui import cli
  File "/home/sag/.local/lib/python3.10/site-packages/pinion/ui.py", line 8, in <module>
    from pinion.generate import generateDrawnImages
  File "/home/sag/.local/lib/python3.10/site-packages/pinion/generate.py", line 12, in <module>
    from pcbdraw.pcbdraw import svg2ki
ModuleNotFoundError: No module named 'pcbdraw.pcbdraw'

```

**Comment by yaqwsx** [comment]
I made a new release (v1.0.1) that fixes this mess during v1.0.0 release.
