### ISSUE TITLE
Running the script without install is broken

### ISSUE THREAD

**Issue by set-soft** [yaqwsx/PcbDraw#49]
I'll try to fix it, but right now I get:

```
$ pcbdraw/pcbdraw.py --version
Traceback (most recent call last):
  File "pcbdraw/pcbdraw.py", line 21, in <module>
    from pcbdraw import __version__
  File "/...absolute_path_in_my_system.../pcbdraw/pcbdraw.py", line 21, in <module>
    from pcbdraw import __version__
ImportError: cannot import name '__version__' from partially initialized module 'pcbdraw' (most likely due to a circular import) (/...absolute_path_in_my_system.../pcbdraw/pcbdraw.py)
```

**Comment by yaqwsx** [comment]
Fixed in #50
