### ISSUE TITLE
kicad 6.0 +  windows 10 installation guide request add one more option

### ISSUE THREAD

**Issue by plazmax** [yaqwsx/PcbDraw#80]
Hello,
windows 10 updated and latest build with Kicad 6.0
installed pcbdraw without issues but hen i tried "pcbdraw --help" or "pcbdraw" command get theese errors :

```
C:\Users\Asus\Documents\kicad\6.0>pcbdraw
Traceback (most recent call last):
  File "C:\Program Files\KiCad\6.0\bin\Lib\site-packages\wand\api.py", line 151, in <module>
    libraries = load_library()
  File "C:\Program Files\KiCad\6.0\bin\Lib\site-packages\wand\api.py", line 140, in load_library
    raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
OSError: cannot find library; tried paths: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\KiCad\6.0\bin\Lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\KiCad\6.0\bin\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\KiCad\6.0\bin\Scripts\pcbdraw.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\KiCad\6.0\bin\Lib\site-packages\pcbdraw\pcbdraw.py", line 16, in <module>
    from wand.api import library
  File "C:\Program Files\KiCad\6.0\bin\Lib\site-packages\wand\api.py", line 175, in <module>
    raise ImportError('MagickWand shared library not found.\n'
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  https://docs.wand-py.org/en/latest/guide/install.html#install-imagemagick-on-windows
```

i think install guide need some update too for windows ;

1.  ImageMagick library need to be installed (like mine fresh windows and kicad installations)
     https://imagemagick.org/script/download.php#windows

![resim](https://user-images.githubusercontent.com/11939537/147499827-575cd6b2-bad8-4795-a1cc-bb84920f083d.png)

![resim](https://user-images.githubusercontent.com/11939537/147499795-84171203-5561-4240-8ae4-720ece1717fd.png)

after that voila :
```
* KiCad 6.0 Command Prompt
************************************
You may now invoke python or pip targeting kicad's install


C:\Users\Asus\Documents\kicad\6.0>pcbdraw
usage: pcbdraw [-h] [--version] [-s STYLE] [-l LIBS] [-p] [-m REMAP] [-c] [--no-drillholes] [-b] [--mirror]
               [-a HIGHLIGHT] [-f FILTER] [-v] [--silent] [--dpi DPI] [--no-warn-back] [--shrink SHRINK]
               board output
pcbdraw: error: the following arguments are required: board, output

C:\Users\Asus\Documents\kicad\6.0>pcbdraw -- help
usage: pcbdraw [-h] [--version] [-s STYLE] [-l LIBS] [-p] [-m REMAP] [-c] [--no-drillholes] [-b] [--mirror]
               [-a HIGHLIGHT] [-f FILTER] [-v] [--silent] [--dpi DPI] [--no-warn-back] [--shrink SHRINK]
               board output
pcbdraw: error: the following arguments are required: output
```

Thanks for your great work and plugins.

**Comment by yaqwsx** [comment]
I added the notes you suggested in 2c0165c
